version: '3.8'

services:
  pawn-shop-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawn-shop-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://pawnshop-683608653401.asia-southeast1.run.app}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Pawn Shop System}
      - NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION:-1.0.0}
      - NEXT_PUBLIC_TIMEOUT=${NEXT_PUBLIC_TIMEOUT:-30000}
      - NEXT_PUBLIC_ENABLE_DEBUG=${NEXT_PUBLIC_ENABLE_DEBUG:-false}
    restart: unless-stopped
    networks:
      - pawn-shop-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://pawnshop-683608653401.asia-southeast1.run.app/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pawn-shop-network:
    driver: bridge 